apiVersion: v1
kind: Secret
metadata:
  name: fragtracker-secrets
  namespace: esport-prod
type: Opaque
stringData: # stringData автоматично кодує у Base64 при розгортанні
  db-password: "PwnedPassword!1337"
  # Токен, який просили у завданні
  Steam__WebHookToken: "VALVE-SECRET-888"
